---
AllCops:
  TargetRubyVersion: 2.3.3
  Exclude:
    - "bin/*"
  DisplayCopNames: true
Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 20
Metrics/ClassLength:
  Max: 200

Rails:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false
